# Autogenerated script from write_hisat2_script.R
# date Tue Jan 21 14:42:28 2020
# make sure directory paths exist before running script
#!/bin/bash
#$ -S /bin/bash
#$ -pe smp 4
#$ -cwd
#$ -N hisat2-array
#$ -j y
#$ -l h_vmem=5G
#$ -t 1-16



module load bioinformatics/hisat2/2.0.4



# Parse parameter file to get variables.
number=$SGE_TASK_ID
paramfile=hisat2_param.txt
 
inr1=`sed -n ${number}p $paramfile | awk '{print $1}'`
outsam=`sed -n ${number}p $paramfile | awk '{print $2}'`

# 9. Run the program.
hisat2 --trim5 10 -x /users/k1625253/brc_scratch/Data/MetaData/GenomeIndex/mm10_hisat2/genome -U $inr1 -S $outsam



