# Autogenerated script from write_trimmomatic_script.R
# date Tue Jan 21 14:21:57 2020
# make sure directory paths exist before running script
#!/bin/bash
#$ -S /bin/bash
#$ -pe smp 1
#$ -cwd
#$ -N trim-array
#$ -j y
#$ -l h_vmem=19G
#$ -t 1-16



module load general/JRE/1.8.0_65
module load bioinformatics/trimmomatic/0.36



# Parse parameter file to get variables.
number=$SGE_TASK_ID
paramfile=trimmomatic_param.txt
 
inr1=`sed -n ${number}p $paramfile | awk '{print $1}'`
outr1=`sed -n ${number}p $paramfile | awk '{print $2}'`

# 9. Run the program.
java -jar /opt/apps/bioinformatics/trimmomatic/0.36/trimmomatic-0.36.jar SE  $inr1 $outr1 ILLUMINACLIP:/users/k1625253/brc_scratch/Data/MetaData/trimmomatic_adapters.fa:2:30:10:8:true



